/* 
interface iterator {
  record row {
    value: string,
    done: bool,
  }

  next: func() -> row
}
*/
default world utils2 {
  // import itr: self.iterator

  export hello: func(name: string) -> string
}
