dist: bionic
language: node_js
node_js:
  - "12"
addons:
  chrome: stable
env:
  global:
    # EM_USE_GLOBAL_CACHE=1 tells emscripten to use precompiled libraries from
    # the emscripten-libs-asmjs package. This speeds up the build significantly.
    - EM_USE_GLOBAL_CACHE=1
install:
  - npm ci
  - sudo apt-get install -y git cmake wget
  - sudo apt-get install -y gcc-multilib g++-multilib pkg-config autoconf bison libtool flex zlib1g-dev
  - sudo apt-get install -y python2.7 python-pip
  - npm run install-build-deps
before_script:
  - npm run lint
  - npm run build
