dist: bionic
language: node_js
node_js:
  - "12"
addons:
  chrome: stable
env:
  global:
    # EM_USE_GLOBAL_CACHE=1 tells emscripten to use precompiled libraries from
    # the emscripten-libs-asmjs package. This speeds up the build significantly.
    - EM_USE_GLOBAL_CACHE=1
install:
  - npm ci
  - npm run install-prerequisites
  - npm run install-build-deps
before_script:
  - npm run lint;
  - npm run build;
