dist: xenial
language: node_js
node_js:
  - '10'
addons:
  chrome: stable
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.emscripten_cache/asmjs"
install:
  - npm ci
before_script:
  - npm run lint;
  - npm run build;
