set(VCPKG_ENV_PASSTHROUGH_UNTRACKED WASI_SDK_PREFIX PATH)

if(NOT DEFINED ENV{WASI_SDK_PREFIX})
   find_path(WASI_SDK_PREFIX "wasi_snapshot_preview1.command.wasm" HINTS ${CMAKE_CURRENT_SOURCE_DIR}/../wasi-sdk-20.0)
else()
   set(WASI_SDK_PREFIX "$ENV{WASI_SDK_PREFIX}")
endif()

message("CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
message("WASI_SDK_PREFIX: ${WASI_SDK_PREFIX}")

if(NOT EXISTS "${WASI_SDK_PREFIX}/share/cmake/wasi-sdk.cmake")
   message(FATAL_ERROR "wasi-sdk.cmake toolchain file not found")
endif()

set(ENV{WASI_SDK_PREFIX} "${WASI_SDK_PREFIX}")
set(VCPKG_CMAKE_SYSTEM_NAME WASI)
set(VCPKG_CMAKE_SYSTEM_VERSION 1)
# set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
# set(VCPKG_MAKE_BUILD_TRIPLET "--host=wasm32-wasi")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${WASI_SDK_PREFIX}/share/cmake/wasi-sdk.cmake")
# set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -D_WASI_EMULATED_SIGNAL")
# set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -D_WASI_EMULATED_SIGNAL")
# set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_WASI_EMULATED_SIGNAL -fno-exceptions -mexec-model=reactor --sysroot=${WASI_SDK_PREFIX}/share/wasi-sysroot")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_WASI_EMULATED_SIGNAL -fno-exceptions -mexec-model=reactor --sysroot=${WASI_SDK_PREFIX}/share/wasi-sysroot")
